### ISSUE TITLE
works in 'output' folder and with .mp4,  not on other folders, file types

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/vidlengths#1]
maybe this is just a formatting thing but when i direct the script to another folder (e.g. Desktop instead of 'data') i get this:
elikab01:vidlengths elikab$ python vidlengths.py /Users/elikab/Desktop/ eb_vidlengths.csv
Traceback (most recent call last):
  File "vidlengths.py", line 32, in <module>
    walk_tree(start_dir)
  File "vidlengths.py", line 24, in walk_tree
    length = metadata.streams[0].durationSeconds()
IndexError: list index out of range

**Comment by ebergelson** [comment]
works on .mp4 not on .mov

**Comment by ebergelson** [comment]
works on .mp4 not on .mov, would be nice to be able to specify which extensions to include and/or specify what the default assumption is as a message in the command line. (also time in seconds is fine)

**Comment by andreiamatuni** [comment]
Not sure at this point why running it on your Desktop is throwing that error, but as far as the file formats, the current script explicitly looks for files ending with .mp4. I can change that check to include whatever file formats necessary. What other file formats besides .mov should it be able to handle? I'll make the file format user specifiable from the command line and have it print what the default is otherwise.
